app = "quintal"
primary_region = "gru"

[build]

[env]
  PORT = "8080"
  PHX_HOST = "quintal.blog.br"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
